/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package concursopreguntas.vistas;

/**
 *
 * @author Baloo
 */
public class JFMenuPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form JFMenuPrincipal
     */
    public JFMenuPrincipal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bntMate = new javax.swing.JButton();
        btnHistoria = new javax.swing.JButton();
        btnCulturaGeneral = new javax.swing.JButton();
        bntProgramacion = new javax.swing.JButton();
        btnCiencia = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        bntMate.setText("Matematicas");
        bntMate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bntMateActionPerformed(evt);
            }
        });

        btnHistoria.setText("Historia");
        btnHistoria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHistoriaActionPerformed(evt);
            }
        });

        btnCulturaGeneral.setText("Cultura General");
        btnCulturaGeneral.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCulturaGeneralActionPerformed(evt);
            }
        });

        bntProgramacion.setText("Programación");
        bntProgramacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bntProgramacionActionPerformed(evt);
            }
        });

        btnCiencia.setText("Ciencia");
        btnCiencia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCienciaActionPerformed(evt);
            }
        });

        jLabel1.setText("¿Quien Quiere Ser Millonario?");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnCiencia)
                .addGap(161, 161, 161))
            .addGroup(layout.createSequentialGroup()
                .addGap(56, 56, 56)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(bntMate)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnHistoria)
                        .addGap(71, 71, 71))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnCulturaGeneral)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 79, Short.MAX_VALUE)
                        .addComponent(bntProgramacion)
                        .addGap(61, 61, 61))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(77, 77, 77)
                        .addComponent(jLabel1)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bntMate)
                    .addComponent(btnHistoria))
                .addGap(37, 37, 37)
                .addComponent(btnCiencia)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 36, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCulturaGeneral)
                    .addComponent(bntProgramacion))
                .addGap(83, 83, 83))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bntMateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bntMateActionPerformed
        // TODO add your handling code here:
        JFCategoriaMate CatMatematica=new JFCategoriaMate();
        CatMatematica.setVisible(true);
    }//GEN-LAST:event_bntMateActionPerformed

    private void btnHistoriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHistoriaActionPerformed
        // TODO add your handling code here:
        JFCategoriaHistoria CatHistoria=new JFCategoriaHistoria();
        CatHistoria.setVisible(true);
    }//GEN-LAST:event_btnHistoriaActionPerformed

    private void btnCienciaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCienciaActionPerformed
        // TODO add your handling code here:
        JFCategoriaCiencia CatCiencia=new JFCategoriaCiencia();
        CatCiencia.setVisible(true);
    }//GEN-LAST:event_btnCienciaActionPerformed

    private void btnCulturaGeneralActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCulturaGeneralActionPerformed
        // TODO add your handling code here:
        JFCategoriaCulturaGeneral CatCulturaGeneral=new JFCategoriaCulturaGeneral();
        CatCulturaGeneral.setVisible(true);
    }//GEN-LAST:event_btnCulturaGeneralActionPerformed

    private void bntProgramacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bntProgramacionActionPerformed
        // TODO add your handling code here:
        JFCategoriaProgramacion CatProgramacion=new JFCategoriaProgramacion();
        CatProgramacion.setVisible(true);
    }//GEN-LAST:event_bntProgramacionActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFMenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFMenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFMenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFMenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFMenuPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bntMate;
    private javax.swing.JButton bntProgramacion;
    private javax.swing.JButton btnCiencia;
    private javax.swing.JButton btnCulturaGeneral;
    private javax.swing.JButton btnHistoria;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
